image: "archlinux:latest"

lint:
  script:
    - pacman -Syu --needed --noconfirm make shellcheck
    - make check

test:
  script:
    - pacman -Syu --needed --noconfirm podman make
    - make test DOCKER=podman
  tags:
    - vm

code-coverage:
  script:
    - pacman -Syu --needed --noconfirm podman make jq
    - make test-coverage DOCKER=podman 2>/dev/null
    - "echo \"Percent coverage: $(jq -r .percent_covered coverage/bats.*/coverage.json)%\""
  tags:
    - vm
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/bats.*/cobertura.xml
