#!/bin/bash

if [ $# -le 0 ]; then
    echo "usage: $(basename 0) <packagename> [<packagename> [<packagename ...]]"
    exit 0
fi

for pkg in $@; do
    echo "==> Moving package '$pkg'"
    $(dirname $0)/db-move "$pkg" "community-testing" "community" "any"
done
