#!/bin/bash
#
# Converts an existing architecture-independent package
# for i686 or x86_64 into a package with "arch = any"
#

# -- Abhishek Dasgupta <abhidg@gmail.com>

[ "$UID" = "" ] && UID=$(uid)
OUTDIR="$(pwd)"
WORKDIR="/tmp/convert-to-any.$UID"

if [ $# -ne 1 ]; then
    echo "Syntax: $(basename $0) <package-file>"
    exit 1
fi

if [ -f /etc/makepkg.conf ]; then
    . /etc/makepkg.conf
else
    echo "E: /etc/makepkg.conf does not exist."
    exit 1
fi

cleanup() {
    trap '' 0 2
    rm -rf "$WORKDIR"
    [ "$1" ] && exit $1
}

ctrl_c() {
    echo "Interrupted" >&2
    cleanup 0
}

die() {
    echo "$*" >&2
    cleanup 1
}

mkdir -p "$WORKDIR/build"

oldpkgname="$1"

if [ -z "$oldpkgname" ]; then
    die "convert-to-any: which package to convert?"
fi

pkg="$(basename $oldpkgname)"
newpkgname=$(echo $pkg | sed "s/-\(i686\|x86_64\)$PKGEXT/-any$PKGEXT/")

if ! cp "$oldpkgname" "$WORKDIR/build/$pkg"; then
    die "convert-to-any: failed to copy package to $WORKDIR"
fi
pushd "$WORKDIR/build" >/dev/null

# Conversion of i686 package into "any" package.
mkdir -p package
if ! fakeroot bsdtar xf "$pkg" -C package; then
	die "convert-to-any: error in extracting $oldpkgname"
fi

sed -i "s/arch = \(i686\|x86_64\)/arch = any/g" package/.PKGINFO
pushd package >/dev/null
fakeroot bsdtar cf "$OUTDIR/$newpkgname" .PKGINFO *
popd >/dev/null

popd >/dev/null
cleanup
