#!/bin/bash
# $Id: db-arch,v 1.22 2005/06/21 03:44:57 judd Exp $

repoid=1
reponame="current"

ftppath="/home/ftp/current/os/i686"

cvspath="/home/cvs-arch"
cvsmod="arch/build"

# call the real script
. `dirname $0`/db-inc

