#!/bin/bash
# $Id: db-extra64,v 1.1 2006/05/05 01:38:33 judd Exp $

repoid=2
reponame="extra"
arch="x86_64"

ftppath="/home/ftp/extra/os/x86_64"

cvspath="/home/cvs-extra"
cvsmod="extra"
cvstag="CURRENT-64"

stagedir="/home/arch64/staging/extra"

# call the real script
. `dirname $0`/db-inc

