#!/bin/bash

if [ $# -ne 3 ]; then
	echo "usage: $(basename $0) <pkgname|packagebase> <reponame> <arch>"
	exit 1
fi

. "$(dirname $0)/db-functions"
. "$(dirname $0)/config"

packagebase="$1"
reponame="$2"
_arch="$3"

ftppath="$FTP_BASE/$reponame/os"
svnrepo="$reponame-$_arch"

[ "$UID" = "" ] && UID=$(uid)

WORKDIR="$TMPDIR/db-remove.$svnrepo.$UID"

cleanup() {
    trap '' 0 2
	# unlock
	repo_unlock $reponame $_arch
	rm -rf "$WORKDIR"
	[ "$1" ] && exit $1
}

ctrl_c() {
	echo "Interrupted" >&2
	cleanup 0
}

die() {
	echo "$*" >&2
	cleanup 1
}

trap ctrl_c 2
trap cleanup 0

repo_lock $reponame $_arch || exit 1

echo -n "Removing $packagebase from $reponame..."
/bin/mkdir -p "$WORKDIR"
cd "$WORKDIR"
/usr/bin/svn checkout -q -N $SVNREPO checkout >/dev/null
cd checkout

/usr/bin/svn up -q $packagebase
if [ -d "$packagebase/repos/$svnrepo" ]; then
	. "$packagebase/repos/$svnrepo/PKGBUILD"
	/usr/bin/svn rm --force -q "$packagebase/repos/$svnrepo"
	/usr/bin/svn commit -q -m "$(basename $0): $packagebase removed by $(id -un)"
else
	die "Error: $packagebase not found in $svnrepo"
fi

cd "$WORKDIR"

if [ "$_arch" == "any" ]; then
	arches="i686 x86_64"
else
	arches="$_arch"
fi

# copy the db file into our working area
for arch in $arches; do
	if [ ! -f "$ftppath/$arch/$reponame$DBEXT" ]; then
		die "No database found at '$ftppath/$arch', nothing more to do"
	fi

	/usr/bin/repo-remove -q "$ftppath/$arch/$reponame$DBEXT" ${pkgname[@]} >/dev/null
done

echo 'done'

# vim: set ts=4 sw=4 noet ft=sh:
