#!/bin/bash

. "$(dirname $0)/db-functions"
. "$(dirname $0)/config"

if [ $# -lt 3 ]; then
	msg "usage: $(basename $0) <repo> <arch> <pkgfile> ..."
	exit 1
fi

repo="$1"
arch="$2"
pkgfiles=(${@:3})

ftppath="$FTP_BASE/$repo/os"

if ! check_repo_permission $repo; then
	die "You don't have permission to add packages to ${repo}"
fi

if [ "$arch" == "any" ]; then
	tarches=(${ARCHES[@]})
else
	tarches=("$arch")
fi

for tarch in ${tarches[@]}; do
	repo_lock $repo $tarch || exit 1
done

for tarch in ${tarches[@]}; do
	for pkgfile in ${pkgfiles[@]}; do
		if [[ ! -f "${FTP_BASE}/${repo}/os/${arch}/${pkgfile##*/}" ]]; then
			die "Package file ${pkgfile##*/} not found in ${FTP_BASE}/${repo}/os/${arch}/"
		else
			msg "Adding $pkgfile to [$repo]..."
		fi
	done
	arch_repo_add "${repo}" "${tarch}" ${pkgfiles[@]}
	repo_unlock $repo $tarch
done
