#!/bin/bash

. "$(dirname $0)/db-functions"
. "$(dirname $0)/config"

if [ $# -lt 3 ]; then
	msg "usage: $(basename $0) <repo> <arch> <pkgname> ..."
	exit 1
fi

repo="$1"
arch="$2"
pkgnames=(${@:3})

ftppath="$FTP_BASE/$repo/os"

if ! check_repo_permission $repo; then
	die "You don't have permission to remove packages from ${repo}"
fi

if [ "$arch" == "any" ]; then
	tarches=(${ARCHES[@]})
else
	tarches=("$arch")
fi

for tarch in ${tarches[@]}; do
	repo_lock $repo $tarch || exit 1
done

for tarch in ${tarches[@]}; do
	for pkgname in ${pkgnames[@]}; do
		msg "Removing $pkgname from [$repo]..."
	done
	arch_repo_remove "${repo}" "${tarch}" ${pkgnames[@]}
	repo_unlock $repo $tarch
done
