#!/bin/bash

. "$(dirname "$(readlink -e "$0")")/config"
. "$(dirname "$(readlink -e "$0")")/db-functions"

if (( $# < 3 )); then
	msg "usage: %s <repo> <arch> <pkgname> ..." "${0##*/}"
	exit 1
fi

repo="$1"
arch="$2"
pkgnames=("${@:3}")

ftppath="$FTP_BASE/$repo/os"

if ! check_repo_permission "$repo"; then
	die "You don't have permission to remove packages from %s" "$repo"
fi

if [[ $arch = any ]]; then
	tarches=("${ARCHES[@]}")
else
	tarches=("$arch")
fi

for tarch in "${tarches[@]}"; do
	repo_lock "$repo" "$tarch" || exit 1
done

for tarch in "${tarches[@]}"; do
	for pkgname in "${pkgnames[@]}"; do
		msg "Removing %s from [%s]..." "$pkgname" "$repo"
	done
	arch_repo_modify remove "${repo}" "${tarch}" "${pkgnames[@]}"
	repo_unlock "$repo" "$tarch"
done
