#!/bin/bash

. "$(dirname $0)/db-functions"
. "$(dirname $0)/config"

if [ $# -ne 3 ]; then
	msg "usage: $(basename $0) <repo> <arch> <pkgname>"
	exit 1
fi

repo="$1"
arch="$2"
pkgname="$3"

ftppath="$FTP_BASE/$repo/os"

if ! check_repo_permission $repo; then
	die "You don't have permission to remove packages from ${repo}"
fi

if [ "$arch" == "any" ]; then
	tarches=(${ARCHES[@]})
else
	tarches=("$arch")
fi

for tarch in ${tarches[@]}; do
	repo_lock $repo $tarch || exit 1
done

msg "Removing $pkgname from [$repo]..."

for tarch in ${tarches[@]}; do
	arch_repo_remove "${repo}" "${tarch}" ${pkgname}
	repo_unlock $repo $tarch
done
