#!/bin/bash
# $Id: db-unstable,v 1.4 2003/05/24 00:25:59 judd Exp $

echo "==> Generating pacsync2 Database for UNSTABLE..." >&2
cd /tmp
CVS_RSH=ssh CVSROOT=:ext:cvs.archlinux.org:/home/cvs-unstable cvs -q export -r CURRENT unstable
/usr/bin/gensync /tmp/unstable /tmp/unstable.db.tar.gz
[ -f /tmp/unstable.db.tar.gz ] && mv -f /tmp/unstable.db.tar.gz /home/ftp/unstable

cd /tmp/unstable && /arch/pkgdb 3

rm -rf /tmp/unstable

