#!/bin/bash
# $Id: db-unstable,v 1.17 2006/02/20 06:33:40 judd Exp $

repoid=3
reponame="unstable"

ftppath="/home/ftp/unstable/os/i686"

cvspath="/home/cvs-unstable"
cvsmod="unstable"

stagedir="$HOME/staging/unstable"

# call the real script
. `dirname $0`/db-inc

