#!/bin/bash
# $Id: genpkglist,v 1.6 2003/05/21 23:07:33 judd Exp $

#
# genpkglist
#
# Generates a text package database for use with the setup script
#

pkgfile="`pwd`/packages.txt"

cd /tmp/arch/build
rm -f $pkgfile
for category in `find * -type d -maxdepth 0 | grep -v CVS`; do
	cd $category
	for pkg in `/bin/ls`; do
		cd $pkg
		if [ -f PKGBUILD ]; then
			. PKGBUILD
			if [ -f /home/ftp/current/$pkgname-$pkgver-$pkgrel.pkg.tar.gz ]; then
				echo "$category/$pkgname-$pkgver-$pkgrel.pkg.tar.gz" >>$pkgfile
			else
				echo "notice: Missing $pkgname-$pkgver-$pkgrel.pkg.tar.gz in ftp site" >&2
			fi
		fi
		cd ..
	done
	cd ..
done

