#!/bin/bash

if [ $# -le 1 ]; then
    echo "usage: $(basename 0) <arch> <packagename> [<packagename> [<packagename ...]]"
    exit 0
fi

arch=$1; shift

for pkg in $@; do
    echo "==> Moving package '$pkg'"
    $(dirname $0)/db-move "$pkg" "testing" "core" "$arch"
done
