#!/bin/bash

script_lock

. "$(dirname $0)/../db-functions"
. "$(dirname $0)/../config"

get_dir_owner() {
	case $1 in
		core)
			echo "ftp:ftp-arch" ;;
		extra)
			echo "ftp:ftp-extra" ;;
		testing)
			echo "ftp:ftp-extra" ;;
		staging)
			echo "ftp:ftp-extra" ;;
		community)
			echo "root:tusers" ;;
		community-testing)
			echo "root:tusers" ;;
		multilib)
			echo "root:tusers" ;;
		pool/packages)
			echo "ftp:ftp-extra" ;;
		pool/community)
			echo "root:tusers" ;;
	esac
}

#adjust the nice level to run at a lower priority
/usr/bin/renice +10 -p $$ > /dev/null

pushd $FTP_BASE >/dev/null
for d in $(get_repos_for_host); do
	owner="$(get_dir_owner $d)"
	/bin/chown -R $owner $d/os/{any,i686,x86_64}
	/bin/chmod -R g+w $d/os/{any,i686,x86_64}
done
for p in $(get_pkgpool_for_host); do
	owner="$(get_dir_owner $p)"
	/bin/chown $owner $p
	/bin/chmod g+w $p
done
/bin/chmod 555 $FTP_BASE
popd >/dev/null

script_unlock
