#!/bin/bash

basedir="$(dirname $0)"

if [ $# -ne 2 ]; then
    echo "usage: $(basename $0) <repo>[,<repo>,...] <mailto>" >&2
    exit 1
fi

for arch in i686 x86_64; do
    $basedir/check_archlinux/check_packages.py \
        --repos="$1" \
        --abs-tree="/srv/abs/rsync/$arch,/srv/abs/rsync/any" --arch="$arch" |\
        $basedir/devlist-mailer "Integrity Check $arch: $1" "$2"
done
