#!/bin/bash

. "$(dirname $0)/../db-functions"
. "$(dirname $0)/../config"


if [ $# -ne 2 ]; then
    die "usage: $(basename $0) <repo>[,<repo>,...] <mailto>"
fi

for arch in ${ARCHES[@]}; do
    $(dirname $0)/check_archlinux/check_packages.py \
        --repos="$1" \
        --abs-tree="/srv/abs/rsync/$arch,/srv/abs/rsync/any" --arch="$arch" |\
        $(dirname $0)/devlist-mailer "Integrity Check $arch: $1" "$2"
done
